### Generated by rprotoc. DO NOT EDIT!
require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Cheesy
  module Users
    require 'cheesy/users/user.pb'
    class AuthRequest < ::Protobuf::Message
      required :string, :email, 1
      required :string, :hashed_password, 2
    end
  end
end