### Generated by rprotoc. DO NOT EDIT!
require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Cheesy
  module Admin
    require 'cheesy/admin/product.pb'
    require 'cheesy/util.pb'
    class PaymentStatus < ::Protobuf::Enum
      define :PENDING, 0
      define :PROCESSING, 1
      define :APPROVED, 2
      define :DENIED, 3
      define :RETURNED, 4
    end
    class LineItem < ::Protobuf::Message
      required :Product, :product, 1
      required :int32, :quantity, 2
      required :double, :amount, 3
    end
    class Order < ::Protobuf::Message
      optional :string, :guid, 1
      optional :string, :order_number, 2
      repeated :LineItem, :line_items, 3
      required :double, :total, 4
      optional :PaymentStatus, :payment_status, 5, :default => :PENDING
    end
  end
end