require 'protobuf/rpc/service'
require 'cheesy/admin/product.pb'

##	!! DO NOT EDIT THIS FILE !!
## 
##	To implement this service as defined by the protobuf, simply
##	reopen Cheesy::Admin::ProductService and implement each service method:
## 
## module Cheesy
## 	module Admin
## 		class ProductService
## 		
## 			# request -> Cheesy::Admin::ProductFindRequest
## 			# response -> Cheesy::Admin::ProductList
## 			def find
## 				# TODO: implement find
## 			end
## 		
## 		end
## 	end
## end
##

module Cheesy
	module Admin
		class ProductService < Protobuf::Rpc::Service
		  rpc :find, ProductFindRequest, ProductList
		end
	end
end
